services:
  - type: web
    name: cinevault-api
    runtime: node
    plan: free
    buildCommand: pnpm install --frozen-lockfile && cd apps/api && pnpm prisma generate && pnpm prisma:deploy && pnpm build
    startCommand: cd apps/api && pnpm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: TMDB_BASE_URL
        value: https://api.themoviedb.org/3
      - key: TMDB_IMAGE_BASE_URL
        value: https://image.tmdb.org/t/p
      - key: JWT_ACCESS_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 30d
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: TMDB_API_KEY
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: APP_URL
        sync: false
      - key: API_URL
        sync: false
